### ISSUE TITLE
Urheber angeben und Lizenz

### ISSUE THREAD

**Issue by TEbinger** [Mathnix/DigitalerSchaukasten#1]
Es sollte unbedingt der Urheber der Idee angegeben werden mit Link zu seiner Seite

Etwa so
Weiterentwicklung einer gut dokumentierten dee von Lutz Neumeier, die ursprünglich hier veröffentlicht wurde http://neumedier.de/schaukasten.html
Lizenz: ccbysa

**Comment by Mathnix** [comment]
Ich habe das Copyright ergänzt. Dachte das wäre nicht nötig, da ich weder sein Skript verwendet habe und auch die grundlegende Idee mit einem lokalen Webserver etc. sich deutlich von seiner Version unterscheidet, aber ich habe einen entsprechenden Hinweis ergänzt und hoffe das ist jetzt so in Ordnung.
